import {MigrationInterface, QueryRunner} from "typeorm";

export class initDB1635298381706 implements MigrationInterface {
    name = 'initDB1635298381706'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`fm_phone\` DROP FOREIGN KEY \`FK_3796c0f20cddbfce6840776200f\``);
        await queryRunner.query(`ALTER TABLE \`fm_phone\` CHANGE \`id_client\` \`id_client\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_ciudad\` DROP FOREIGN KEY \`FK_41e29c427582948e763288142c1\``);
        await queryRunner.query(`ALTER TABLE \`fm_ciudad\` CHANGE \`id_estado\` \`id_estado\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_parroquia\` DROP FOREIGN KEY \`FK_4ac1c804b1f8dcfc3b08363151f\``);
        await queryRunner.query(`ALTER TABLE \`fm_parroquia\` CHANGE \`id_municipio\` \`id_municipio\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_municipio\` DROP FOREIGN KEY \`FK_9210306e682154252390bb45859\``);
        await queryRunner.query(`ALTER TABLE \`fm_municipio\` CHANGE \`id_estado\` \`id_estado\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_location\` DROP FOREIGN KEY \`FK_61ea978348ae6a36894bd39de24\``);
        await queryRunner.query(`ALTER TABLE \`fm_location\` DROP FOREIGN KEY \`FK_1c57c6523dd537b0ef0a9f5b419\``);
        await queryRunner.query(`ALTER TABLE \`fm_location\` DROP FOREIGN KEY \`FK_3e940da713ea86a9367f70618d0\``);
        await queryRunner.query(`ALTER TABLE \`fm_location\` DROP FOREIGN KEY \`FK_73174abf588e8edc848e2e3a121\``);
        await queryRunner.query(`ALTER TABLE \`fm_location\` CHANGE \`id_estado\` \`id_estado\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_location\` CHANGE \`id_municipio\` \`id_municipio\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_location\` CHANGE \`id_ciudad\` \`id_ciudad\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_location\` CHANGE \`id_parroquia\` \`id_parroquia\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` DROP FOREIGN KEY \`FK_7a14b7e77f8a819735106b016e5\``);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` DROP FOREIGN KEY \`FK_7ef2c34882b3fb18bc366679aa6\``);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` DROP FOREIGN KEY \`FK_9af2a5b750e303f6a4e5870a443\``);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` DROP FOREIGN KEY \`FK_f4754d81e43ea2411cf4a519bc0\``);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` CHANGE \`id_location\` \`id_location\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` CHANGE \`id_commerce\` \`id_commerce\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` CHANGE \`id_request\` \`id_request\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` CHANGE \`id_product\` \`id_product\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_status\` DROP FOREIGN KEY \`FK_fba8ef1cff94c2c7b202d6deb0d\``);
        await queryRunner.query(`ALTER TABLE \`fm_status\` DROP FOREIGN KEY \`FK_65c1dc9c7cb36fda1f2cbf41d71\``);
        await queryRunner.query(`ALTER TABLE \`fm_status\` DROP FOREIGN KEY \`FK_c8e50e7831f97bb4247b9edd91a\``);
        await queryRunner.query(`ALTER TABLE \`fm_status\` CHANGE \`id_request\` \`id_request\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_status\` CHANGE \`id_department\` \`id_department\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_status\` CHANGE \`id_status_request\` \`id_status_request\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_7af3f0d3b144b7d6a72ceac4073\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_e58a708881405ef2655aef9fd81\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_bd495da93173bc09fe6d62b98b5\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_96c58e4419abc60056da31ef769\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_88cdbf21a125980f977d82c27b1\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_8e6a76c31cf8fb8ef74f4823e10\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_f2cb8353f19c168725999701d7d\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_82416fb6e19b7157d05f08584fe\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_af1eae98b17fa9e92881cafce3d\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_b5772edefef68ff71c6477c9705\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_4f207c9a0e9645910383377f86d\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_c4efb1cf02f43090740926bb1fc\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_395407df85335f0e00430aa3876\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_9dd51a6b0f9bc09cd820b0c8076\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`id_payment_method\` \`id_payment_method\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`id_type_payment\` \`id_type_payment\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`id_client\` \`id_client\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`id_commerce\` \`id_commerce\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`id_product\` \`id_product\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`id_type_request\` \`id_type_request\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`id_request_origin\` \`id_request_origin\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`id_valid_request\` \`id_valid_request\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`rc_constitutive_act\` \`rc_constitutive_act\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`rc_special_contributor\` \`rc_special_contributor\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`rc_ref_bank\` \`rc_ref_bank\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`rc_comp_dep\` \`rc_comp_dep\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`rc_rif\` \`rc_rif\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`rc_ident_card\` \`rc_ident_card\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_company\` DROP FOREIGN KEY \`FK_dbee0c02784ebe3f0c0330014b4\``);
        await queryRunner.query(`ALTER TABLE \`fm_company\` CHANGE \`id_commerce\` \`id_commerce\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_worker\` DROP FOREIGN KEY \`FK_e018746d22c55fc0477298963ad\``);
        await queryRunner.query(`ALTER TABLE \`fm_worker\` DROP FOREIGN KEY \`FK_93ed0b26dab2997d685e1ea0e56\``);
        await queryRunner.query(`ALTER TABLE \`fm_worker\` DROP FOREIGN KEY \`FK_b7651b1e49eddd73c4d3a78c0a3\``);
        await queryRunner.query(`DROP INDEX \`IDX_7a21b1b04b3df8909ad71d8909\` ON \`fm_worker\``);
        await queryRunner.query(`ALTER TABLE \`fm_worker\` CHANGE \`id_ident_type\` \`id_ident_type\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_worker\` CHANGE \`id_company\` \`id_company\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_worker\` CHANGE \`id_department\` \`id_department\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_client\` DROP FOREIGN KEY \`FK_2429112946d86e74cfedf59fc6c\``);
        await queryRunner.query(`ALTER TABLE \`fm_client\` DROP FOREIGN KEY \`FK_a4d752b12018c7ffc6a64a65307\``);
        await queryRunner.query(`DROP INDEX \`IDX_15f756dc2a9a6aefe1751f731f\` ON \`fm_client\``);
        await queryRunner.query(`ALTER TABLE \`fm_client\` CHANGE \`id_location\` \`id_location\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_client\` CHANGE \`id_ident_type\` \`id_ident_type\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_bank_commerce\` DROP FOREIGN KEY \`FK_f6a998bb3ed4eb4c244b9baa7f3\``);
        await queryRunner.query(`ALTER TABLE \`fm_bank_commerce\` DROP FOREIGN KEY \`FK_1f3e4561151d389d052b818d1ac\``);
        await queryRunner.query(`ALTER TABLE \`fm_bank_commerce\` DROP FOREIGN KEY \`FK_ac51278339d6ed7a4bcbb5bda7f\``);
        await queryRunner.query(`ALTER TABLE \`fm_bank_commerce\` CHANGE \`id_commerce\` \`id_commerce\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_bank_commerce\` CHANGE \`id_client\` \`id_client\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_bank_commerce\` CHANGE \`id_bank\` \`id_bank\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_afiliados\` DROP FOREIGN KEY \`FK_d82f3abdbeb01e63fce48ca1953\``);
        await queryRunner.query(`ALTER TABLE \`fm_afiliados\` DROP FOREIGN KEY \`FK_9d80d093a993a82cb4e7a1456ef\``);
        await queryRunner.query(`ALTER TABLE \`fm_afiliados\` CHANGE \`id_type_person\` \`id_type_person\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_afiliados\` CHANGE \`id_bank\` \`id_bank\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_activity\` DROP FOREIGN KEY \`FK_7c7fad9604e8f103f82b763a11d\``);
        await queryRunner.query(`ALTER TABLE \`fm_activity\` CHANGE \`id_afiliado\` \`id_afiliado\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` DROP FOREIGN KEY \`FK_363178079b89e15b47a66e5dbd0\``);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` DROP FOREIGN KEY \`FK_9d10e9066e2a479adcf4830e65b\``);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` DROP FOREIGN KEY \`FK_e74342f2c030e08992c56df0af9\``);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` DROP FOREIGN KEY \`FK_ae4a2f524f6c29e5d38f265f7ac\``);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` CHANGE \`id_ident_type\` \`id_ident_type\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` CHANGE \`id_activity\` \`id_activity\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` CHANGE \`id_location\` \`id_location\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` CHANGE \`id_client\` \`id_client\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_aci_commerce\` DROP FOREIGN KEY \`FK_30c2d9c55728a95e712e8373627\``);
        await queryRunner.query(`ALTER TABLE \`fm_aci_commerce\` DROP FOREIGN KEY \`FK_468916a89469c5b93e8b5d8010e\``);
        await queryRunner.query(`ALTER TABLE \`fm_aci_commerce\` CHANGE \`id_commerce\` \`id_commerce\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fm_aci_commerce\` CHANGE \`id_bank\` \`id_bank\` int NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_7a21b1b04b3df8909ad71d8909\` ON \`fm_worker\` (\`id_ident_type\`, \`ident_num\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_15f756dc2a9a6aefe1751f731f\` ON \`fm_client\` (\`id_ident_type\`, \`ident_num\`)`);
        await queryRunner.query(`ALTER TABLE \`fm_phone\` ADD CONSTRAINT \`FK_3796c0f20cddbfce6840776200f\` FOREIGN KEY (\`id_client\`) REFERENCES \`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_ciudad\` ADD CONSTRAINT \`FK_41e29c427582948e763288142c1\` FOREIGN KEY (\`id_estado\`) REFERENCES \`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_parroquia\` ADD CONSTRAINT \`FK_4ac1c804b1f8dcfc3b08363151f\` FOREIGN KEY (\`id_municipio\`) REFERENCES \`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_municipio\` ADD CONSTRAINT \`FK_9210306e682154252390bb45859\` FOREIGN KEY (\`id_estado\`) REFERENCES \`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_location\` ADD CONSTRAINT \`FK_61ea978348ae6a36894bd39de24\` FOREIGN KEY (\`id_estado\`) REFERENCES \`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_location\` ADD CONSTRAINT \`FK_1c57c6523dd537b0ef0a9f5b419\` FOREIGN KEY (\`id_municipio\`) REFERENCES \`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_location\` ADD CONSTRAINT \`FK_3e940da713ea86a9367f70618d0\` FOREIGN KEY (\`id_ciudad\`) REFERENCES \`fm_ciudad\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_location\` ADD CONSTRAINT \`FK_73174abf588e8edc848e2e3a121\` FOREIGN KEY (\`id_parroquia\`) REFERENCES \`fm_parroquia\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` ADD CONSTRAINT \`FK_7a14b7e77f8a819735106b016e5\` FOREIGN KEY (\`id_location\`) REFERENCES \`fm_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` ADD CONSTRAINT \`FK_7ef2c34882b3fb18bc366679aa6\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` ADD CONSTRAINT \`FK_9af2a5b750e303f6a4e5870a443\` FOREIGN KEY (\`id_request\`) REFERENCES \`fm_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` ADD CONSTRAINT \`FK_f4754d81e43ea2411cf4a519bc0\` FOREIGN KEY (\`id_product\`) REFERENCES \`fm_product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_status\` ADD CONSTRAINT \`FK_fba8ef1cff94c2c7b202d6deb0d\` FOREIGN KEY (\`id_request\`) REFERENCES \`fm_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_status\` ADD CONSTRAINT \`FK_65c1dc9c7cb36fda1f2cbf41d71\` FOREIGN KEY (\`id_department\`) REFERENCES \`fm_department\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_status\` ADD CONSTRAINT \`FK_c8e50e7831f97bb4247b9edd91a\` FOREIGN KEY (\`id_status_request\`) REFERENCES \`fm_status_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_7af3f0d3b144b7d6a72ceac4073\` FOREIGN KEY (\`id_payment_method\`) REFERENCES \`fm_payment_method\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_e58a708881405ef2655aef9fd81\` FOREIGN KEY (\`id_type_payment\`) REFERENCES \`fm_type_payment\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_bd495da93173bc09fe6d62b98b5\` FOREIGN KEY (\`id_client\`) REFERENCES \`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_96c58e4419abc60056da31ef769\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_88cdbf21a125980f977d82c27b1\` FOREIGN KEY (\`id_product\`) REFERENCES \`fm_product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_8e6a76c31cf8fb8ef74f4823e10\` FOREIGN KEY (\`id_type_request\`) REFERENCES \`fm_type_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_f2cb8353f19c168725999701d7d\` FOREIGN KEY (\`id_request_origin\`) REFERENCES \`fm_request_origin\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_82416fb6e19b7157d05f08584fe\` FOREIGN KEY (\`id_valid_request\`) REFERENCES \`fm_valid_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_af1eae98b17fa9e92881cafce3d\` FOREIGN KEY (\`rc_constitutive_act\`) REFERENCES \`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_b5772edefef68ff71c6477c9705\` FOREIGN KEY (\`rc_special_contributor\`) REFERENCES \`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_4f207c9a0e9645910383377f86d\` FOREIGN KEY (\`rc_ref_bank\`) REFERENCES \`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_c4efb1cf02f43090740926bb1fc\` FOREIGN KEY (\`rc_comp_dep\`) REFERENCES \`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_395407df85335f0e00430aa3876\` FOREIGN KEY (\`rc_rif\`) REFERENCES \`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_9dd51a6b0f9bc09cd820b0c8076\` FOREIGN KEY (\`rc_ident_card\`) REFERENCES \`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_company\` ADD CONSTRAINT \`FK_dbee0c02784ebe3f0c0330014b4\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`fm_worker\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_worker\` ADD CONSTRAINT \`FK_e018746d22c55fc0477298963ad\` FOREIGN KEY (\`id_ident_type\`) REFERENCES \`fm_ident_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_worker\` ADD CONSTRAINT \`FK_93ed0b26dab2997d685e1ea0e56\` FOREIGN KEY (\`id_company\`) REFERENCES \`fm_company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_worker\` ADD CONSTRAINT \`FK_b7651b1e49eddd73c4d3a78c0a3\` FOREIGN KEY (\`id_department\`) REFERENCES \`fm_department\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_client\` ADD CONSTRAINT \`FK_a4d752b12018c7ffc6a64a65307\` FOREIGN KEY (\`id_ident_type\`) REFERENCES \`fm_ident_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_client\` ADD CONSTRAINT \`FK_2429112946d86e74cfedf59fc6c\` FOREIGN KEY (\`id_location\`) REFERENCES \`fm_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_bank_commerce\` ADD CONSTRAINT \`FK_f6a998bb3ed4eb4c244b9baa7f3\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_bank_commerce\` ADD CONSTRAINT \`FK_1f3e4561151d389d052b818d1ac\` FOREIGN KEY (\`id_client\`) REFERENCES \`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_bank_commerce\` ADD CONSTRAINT \`FK_ac51278339d6ed7a4bcbb5bda7f\` FOREIGN KEY (\`id_bank\`) REFERENCES \`fm_bank\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_afiliados\` ADD CONSTRAINT \`FK_d82f3abdbeb01e63fce48ca1953\` FOREIGN KEY (\`id_type_person\`) REFERENCES \`fm_type_person\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_afiliados\` ADD CONSTRAINT \`FK_9d80d093a993a82cb4e7a1456ef\` FOREIGN KEY (\`id_bank\`) REFERENCES \`fm_bank\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_activity\` ADD CONSTRAINT \`FK_7c7fad9604e8f103f82b763a11d\` FOREIGN KEY (\`id_afiliado\`) REFERENCES \`fm_afiliados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` ADD CONSTRAINT \`FK_363178079b89e15b47a66e5dbd0\` FOREIGN KEY (\`id_ident_type\`) REFERENCES \`fm_ident_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` ADD CONSTRAINT \`FK_9d10e9066e2a479adcf4830e65b\` FOREIGN KEY (\`id_activity\`) REFERENCES \`fm_activity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` ADD CONSTRAINT \`FK_e74342f2c030e08992c56df0af9\` FOREIGN KEY (\`id_location\`) REFERENCES \`fm_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` ADD CONSTRAINT \`FK_ae4a2f524f6c29e5d38f265f7ac\` FOREIGN KEY (\`id_client\`) REFERENCES \`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_aci_commerce\` ADD CONSTRAINT \`FK_30c2d9c55728a95e712e8373627\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_aci_commerce\` ADD CONSTRAINT \`FK_468916a89469c5b93e8b5d8010e\` FOREIGN KEY (\`id_bank\`) REFERENCES \`fm_worker\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`fm_aci_commerce\` DROP FOREIGN KEY \`FK_468916a89469c5b93e8b5d8010e\``);
        await queryRunner.query(`ALTER TABLE \`fm_aci_commerce\` DROP FOREIGN KEY \`FK_30c2d9c55728a95e712e8373627\``);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` DROP FOREIGN KEY \`FK_ae4a2f524f6c29e5d38f265f7ac\``);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` DROP FOREIGN KEY \`FK_e74342f2c030e08992c56df0af9\``);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` DROP FOREIGN KEY \`FK_9d10e9066e2a479adcf4830e65b\``);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` DROP FOREIGN KEY \`FK_363178079b89e15b47a66e5dbd0\``);
        await queryRunner.query(`ALTER TABLE \`fm_activity\` DROP FOREIGN KEY \`FK_7c7fad9604e8f103f82b763a11d\``);
        await queryRunner.query(`ALTER TABLE \`fm_afiliados\` DROP FOREIGN KEY \`FK_9d80d093a993a82cb4e7a1456ef\``);
        await queryRunner.query(`ALTER TABLE \`fm_afiliados\` DROP FOREIGN KEY \`FK_d82f3abdbeb01e63fce48ca1953\``);
        await queryRunner.query(`ALTER TABLE \`fm_bank_commerce\` DROP FOREIGN KEY \`FK_ac51278339d6ed7a4bcbb5bda7f\``);
        await queryRunner.query(`ALTER TABLE \`fm_bank_commerce\` DROP FOREIGN KEY \`FK_1f3e4561151d389d052b818d1ac\``);
        await queryRunner.query(`ALTER TABLE \`fm_bank_commerce\` DROP FOREIGN KEY \`FK_f6a998bb3ed4eb4c244b9baa7f3\``);
        await queryRunner.query(`ALTER TABLE \`fm_client\` DROP FOREIGN KEY \`FK_2429112946d86e74cfedf59fc6c\``);
        await queryRunner.query(`ALTER TABLE \`fm_client\` DROP FOREIGN KEY \`FK_a4d752b12018c7ffc6a64a65307\``);
        await queryRunner.query(`ALTER TABLE \`fm_worker\` DROP FOREIGN KEY \`FK_b7651b1e49eddd73c4d3a78c0a3\``);
        await queryRunner.query(`ALTER TABLE \`fm_worker\` DROP FOREIGN KEY \`FK_93ed0b26dab2997d685e1ea0e56\``);
        await queryRunner.query(`ALTER TABLE \`fm_worker\` DROP FOREIGN KEY \`FK_e018746d22c55fc0477298963ad\``);
        await queryRunner.query(`ALTER TABLE \`fm_company\` DROP FOREIGN KEY \`FK_dbee0c02784ebe3f0c0330014b4\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_9dd51a6b0f9bc09cd820b0c8076\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_395407df85335f0e00430aa3876\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_c4efb1cf02f43090740926bb1fc\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_4f207c9a0e9645910383377f86d\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_b5772edefef68ff71c6477c9705\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_af1eae98b17fa9e92881cafce3d\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_82416fb6e19b7157d05f08584fe\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_f2cb8353f19c168725999701d7d\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_8e6a76c31cf8fb8ef74f4823e10\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_88cdbf21a125980f977d82c27b1\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_96c58e4419abc60056da31ef769\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_bd495da93173bc09fe6d62b98b5\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_e58a708881405ef2655aef9fd81\``);
        await queryRunner.query(`ALTER TABLE \`fm_request\` DROP FOREIGN KEY \`FK_7af3f0d3b144b7d6a72ceac4073\``);
        await queryRunner.query(`ALTER TABLE \`fm_status\` DROP FOREIGN KEY \`FK_c8e50e7831f97bb4247b9edd91a\``);
        await queryRunner.query(`ALTER TABLE \`fm_status\` DROP FOREIGN KEY \`FK_65c1dc9c7cb36fda1f2cbf41d71\``);
        await queryRunner.query(`ALTER TABLE \`fm_status\` DROP FOREIGN KEY \`FK_fba8ef1cff94c2c7b202d6deb0d\``);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` DROP FOREIGN KEY \`FK_f4754d81e43ea2411cf4a519bc0\``);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` DROP FOREIGN KEY \`FK_9af2a5b750e303f6a4e5870a443\``);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` DROP FOREIGN KEY \`FK_7ef2c34882b3fb18bc366679aa6\``);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` DROP FOREIGN KEY \`FK_7a14b7e77f8a819735106b016e5\``);
        await queryRunner.query(`ALTER TABLE \`fm_location\` DROP FOREIGN KEY \`FK_73174abf588e8edc848e2e3a121\``);
        await queryRunner.query(`ALTER TABLE \`fm_location\` DROP FOREIGN KEY \`FK_3e940da713ea86a9367f70618d0\``);
        await queryRunner.query(`ALTER TABLE \`fm_location\` DROP FOREIGN KEY \`FK_1c57c6523dd537b0ef0a9f5b419\``);
        await queryRunner.query(`ALTER TABLE \`fm_location\` DROP FOREIGN KEY \`FK_61ea978348ae6a36894bd39de24\``);
        await queryRunner.query(`ALTER TABLE \`fm_municipio\` DROP FOREIGN KEY \`FK_9210306e682154252390bb45859\``);
        await queryRunner.query(`ALTER TABLE \`fm_parroquia\` DROP FOREIGN KEY \`FK_4ac1c804b1f8dcfc3b08363151f\``);
        await queryRunner.query(`ALTER TABLE \`fm_ciudad\` DROP FOREIGN KEY \`FK_41e29c427582948e763288142c1\``);
        await queryRunner.query(`ALTER TABLE \`fm_phone\` DROP FOREIGN KEY \`FK_3796c0f20cddbfce6840776200f\``);
        await queryRunner.query(`DROP INDEX \`IDX_15f756dc2a9a6aefe1751f731f\` ON \`fm_client\``);
        await queryRunner.query(`DROP INDEX \`IDX_7a21b1b04b3df8909ad71d8909\` ON \`fm_worker\``);
        await queryRunner.query(`ALTER TABLE \`fm_aci_commerce\` CHANGE \`id_bank\` \`id_bank\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_aci_commerce\` CHANGE \`id_commerce\` \`id_commerce\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_aci_commerce\` ADD CONSTRAINT \`FK_468916a89469c5b93e8b5d8010e\` FOREIGN KEY (\`id_bank\`) REFERENCES \`fm_worker\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_aci_commerce\` ADD CONSTRAINT \`FK_30c2d9c55728a95e712e8373627\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` CHANGE \`id_client\` \`id_client\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` CHANGE \`id_location\` \`id_location\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` CHANGE \`id_activity\` \`id_activity\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` CHANGE \`id_ident_type\` \`id_ident_type\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` ADD CONSTRAINT \`FK_ae4a2f524f6c29e5d38f265f7ac\` FOREIGN KEY (\`id_client\`) REFERENCES \`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` ADD CONSTRAINT \`FK_e74342f2c030e08992c56df0af9\` FOREIGN KEY (\`id_location\`) REFERENCES \`fm_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` ADD CONSTRAINT \`FK_9d10e9066e2a479adcf4830e65b\` FOREIGN KEY (\`id_activity\`) REFERENCES \`fm_activity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_commerce\` ADD CONSTRAINT \`FK_363178079b89e15b47a66e5dbd0\` FOREIGN KEY (\`id_ident_type\`) REFERENCES \`fm_ident_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_activity\` CHANGE \`id_afiliado\` \`id_afiliado\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_activity\` ADD CONSTRAINT \`FK_7c7fad9604e8f103f82b763a11d\` FOREIGN KEY (\`id_afiliado\`) REFERENCES \`fm_afiliados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_afiliados\` CHANGE \`id_bank\` \`id_bank\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_afiliados\` CHANGE \`id_type_person\` \`id_type_person\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_afiliados\` ADD CONSTRAINT \`FK_9d80d093a993a82cb4e7a1456ef\` FOREIGN KEY (\`id_bank\`) REFERENCES \`fm_bank\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_afiliados\` ADD CONSTRAINT \`FK_d82f3abdbeb01e63fce48ca1953\` FOREIGN KEY (\`id_type_person\`) REFERENCES \`fm_type_person\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_bank_commerce\` CHANGE \`id_bank\` \`id_bank\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_bank_commerce\` CHANGE \`id_client\` \`id_client\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_bank_commerce\` CHANGE \`id_commerce\` \`id_commerce\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_bank_commerce\` ADD CONSTRAINT \`FK_ac51278339d6ed7a4bcbb5bda7f\` FOREIGN KEY (\`id_bank\`) REFERENCES \`fm_bank\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_bank_commerce\` ADD CONSTRAINT \`FK_1f3e4561151d389d052b818d1ac\` FOREIGN KEY (\`id_client\`) REFERENCES \`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_bank_commerce\` ADD CONSTRAINT \`FK_f6a998bb3ed4eb4c244b9baa7f3\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_client\` CHANGE \`id_ident_type\` \`id_ident_type\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_client\` CHANGE \`id_location\` \`id_location\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_15f756dc2a9a6aefe1751f731f\` ON \`fm_client\` (\`id_ident_type\`, \`ident_num\`)`);
        await queryRunner.query(`ALTER TABLE \`fm_client\` ADD CONSTRAINT \`FK_a4d752b12018c7ffc6a64a65307\` FOREIGN KEY (\`id_ident_type\`) REFERENCES \`fm_ident_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_client\` ADD CONSTRAINT \`FK_2429112946d86e74cfedf59fc6c\` FOREIGN KEY (\`id_location\`) REFERENCES \`fm_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_worker\` CHANGE \`id_department\` \`id_department\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_worker\` CHANGE \`id_company\` \`id_company\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_worker\` CHANGE \`id_ident_type\` \`id_ident_type\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_7a21b1b04b3df8909ad71d8909\` ON \`fm_worker\` (\`id_ident_type\`, \`ident_num\`)`);
        await queryRunner.query(`ALTER TABLE \`fm_worker\` ADD CONSTRAINT \`FK_b7651b1e49eddd73c4d3a78c0a3\` FOREIGN KEY (\`id_department\`) REFERENCES \`fm_department\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_worker\` ADD CONSTRAINT \`FK_93ed0b26dab2997d685e1ea0e56\` FOREIGN KEY (\`id_company\`) REFERENCES \`fm_company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_worker\` ADD CONSTRAINT \`FK_e018746d22c55fc0477298963ad\` FOREIGN KEY (\`id_ident_type\`) REFERENCES \`fm_ident_type\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_company\` CHANGE \`id_commerce\` \`id_commerce\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_company\` ADD CONSTRAINT \`FK_dbee0c02784ebe3f0c0330014b4\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`fm_worker\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`rc_ident_card\` \`rc_ident_card\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`rc_rif\` \`rc_rif\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`rc_comp_dep\` \`rc_comp_dep\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`rc_ref_bank\` \`rc_ref_bank\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`rc_special_contributor\` \`rc_special_contributor\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`rc_constitutive_act\` \`rc_constitutive_act\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`id_valid_request\` \`id_valid_request\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`id_request_origin\` \`id_request_origin\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`id_type_request\` \`id_type_request\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`id_product\` \`id_product\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`id_commerce\` \`id_commerce\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`id_client\` \`id_client\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`id_type_payment\` \`id_type_payment\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` CHANGE \`id_payment_method\` \`id_payment_method\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_9dd51a6b0f9bc09cd820b0c8076\` FOREIGN KEY (\`rc_ident_card\`) REFERENCES \`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_395407df85335f0e00430aa3876\` FOREIGN KEY (\`rc_rif\`) REFERENCES \`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_c4efb1cf02f43090740926bb1fc\` FOREIGN KEY (\`rc_comp_dep\`) REFERENCES \`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_4f207c9a0e9645910383377f86d\` FOREIGN KEY (\`rc_ref_bank\`) REFERENCES \`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_b5772edefef68ff71c6477c9705\` FOREIGN KEY (\`rc_special_contributor\`) REFERENCES \`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_af1eae98b17fa9e92881cafce3d\` FOREIGN KEY (\`rc_constitutive_act\`) REFERENCES \`fm_photo\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_82416fb6e19b7157d05f08584fe\` FOREIGN KEY (\`id_valid_request\`) REFERENCES \`fm_valid_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_f2cb8353f19c168725999701d7d\` FOREIGN KEY (\`id_request_origin\`) REFERENCES \`fm_request_origin\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_8e6a76c31cf8fb8ef74f4823e10\` FOREIGN KEY (\`id_type_request\`) REFERENCES \`fm_type_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_88cdbf21a125980f977d82c27b1\` FOREIGN KEY (\`id_product\`) REFERENCES \`fm_product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_96c58e4419abc60056da31ef769\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_bd495da93173bc09fe6d62b98b5\` FOREIGN KEY (\`id_client\`) REFERENCES \`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_e58a708881405ef2655aef9fd81\` FOREIGN KEY (\`id_type_payment\`) REFERENCES \`fm_type_payment\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_request\` ADD CONSTRAINT \`FK_7af3f0d3b144b7d6a72ceac4073\` FOREIGN KEY (\`id_payment_method\`) REFERENCES \`fm_payment_method\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_status\` CHANGE \`id_status_request\` \`id_status_request\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_status\` CHANGE \`id_department\` \`id_department\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_status\` CHANGE \`id_request\` \`id_request\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_status\` ADD CONSTRAINT \`FK_c8e50e7831f97bb4247b9edd91a\` FOREIGN KEY (\`id_status_request\`) REFERENCES \`fm_status_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_status\` ADD CONSTRAINT \`FK_65c1dc9c7cb36fda1f2cbf41d71\` FOREIGN KEY (\`id_department\`) REFERENCES \`fm_department\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_status\` ADD CONSTRAINT \`FK_fba8ef1cff94c2c7b202d6deb0d\` FOREIGN KEY (\`id_request\`) REFERENCES \`fm_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` CHANGE \`id_product\` \`id_product\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` CHANGE \`id_request\` \`id_request\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` CHANGE \`id_commerce\` \`id_commerce\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` CHANGE \`id_location\` \`id_location\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` ADD CONSTRAINT \`FK_f4754d81e43ea2411cf4a519bc0\` FOREIGN KEY (\`id_product\`) REFERENCES \`fm_product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` ADD CONSTRAINT \`FK_9af2a5b750e303f6a4e5870a443\` FOREIGN KEY (\`id_request\`) REFERENCES \`fm_request\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` ADD CONSTRAINT \`FK_7ef2c34882b3fb18bc366679aa6\` FOREIGN KEY (\`id_commerce\`) REFERENCES \`fm_commerce\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_dir_pos\` ADD CONSTRAINT \`FK_7a14b7e77f8a819735106b016e5\` FOREIGN KEY (\`id_location\`) REFERENCES \`fm_location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_location\` CHANGE \`id_parroquia\` \`id_parroquia\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_location\` CHANGE \`id_ciudad\` \`id_ciudad\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_location\` CHANGE \`id_municipio\` \`id_municipio\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_location\` CHANGE \`id_estado\` \`id_estado\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_location\` ADD CONSTRAINT \`FK_73174abf588e8edc848e2e3a121\` FOREIGN KEY (\`id_parroquia\`) REFERENCES \`fm_parroquia\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_location\` ADD CONSTRAINT \`FK_3e940da713ea86a9367f70618d0\` FOREIGN KEY (\`id_ciudad\`) REFERENCES \`fm_ciudad\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_location\` ADD CONSTRAINT \`FK_1c57c6523dd537b0ef0a9f5b419\` FOREIGN KEY (\`id_municipio\`) REFERENCES \`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_location\` ADD CONSTRAINT \`FK_61ea978348ae6a36894bd39de24\` FOREIGN KEY (\`id_estado\`) REFERENCES \`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_municipio\` CHANGE \`id_estado\` \`id_estado\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_municipio\` ADD CONSTRAINT \`FK_9210306e682154252390bb45859\` FOREIGN KEY (\`id_estado\`) REFERENCES \`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_parroquia\` CHANGE \`id_municipio\` \`id_municipio\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_parroquia\` ADD CONSTRAINT \`FK_4ac1c804b1f8dcfc3b08363151f\` FOREIGN KEY (\`id_municipio\`) REFERENCES \`fm_municipio\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_ciudad\` CHANGE \`id_estado\` \`id_estado\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_ciudad\` ADD CONSTRAINT \`FK_41e29c427582948e763288142c1\` FOREIGN KEY (\`id_estado\`) REFERENCES \`fm_estado\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fm_phone\` CHANGE \`id_client\` \`id_client\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fm_phone\` ADD CONSTRAINT \`FK_3796c0f20cddbfce6840776200f\` FOREIGN KEY (\`id_client\`) REFERENCES \`fm_client\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
