export const relationsFM = [
	'id_request',
	'id_request.id_client',
	'id_request.id_client.id_location',
	'id_request.id_client.id_location.id_direccion',
	'id_request.id_client.rc_ident_card',
	'id_request.id_client.id_ident_type',
	'id_request.id_client.phones',
	//
	'id_request.id_commerce',
	'id_request.id_commerce.id_ident_type',
	'id_request.id_commerce.id_activity',
	'id_request.id_commerce.id_location',
	'id_request.id_commerce.id_location.id_direccion',
	'id_request.id_commerce.banks',
	'id_request.id_commerce.rc_constitutive_act',
	'id_request.id_commerce.rc_constitutive_act.id_photo',
	'id_request.id_commerce.rc_rif',
	'id_request.id_commerce.rc_special_contributor',
	'id_request.id_commerce.id_aci',
	//
	'id_request.rc_planilla',
	'id_request.rc_planilla.id_photo',
	'id_request.pos',
	'id_request.pos.id_location',
	'id_request.pos.id_location.id_direccion',
	//
	'pos',
	'pos.id_product',
	'id_request.id_type_request',
	'id_request.id_request_origin',
	//
	'id_request.rc_ref_bank',
	'id_request.rc_comp_dep',
	'id_request.id_payment_method',
	'id_request.id_type_payment',
	//Fm
	'id_request.id_valid_request',
];
